<?php

use Drupal\Core\Form\FormStateInterface;

function attraction_tickets_theme()
{
    return [
        'ats_product_list' => [
            'variables' => ['data' => NULL],
        ],
        'form__search_form' => [
            // base_hook is important!
            // Otherwise your template won't know what to render.
            'base hook' => 'form',
        ],
    ];
}

function attraction_tickets_theme_suggestions_alter(array &$suggestions, array $variables)
{
    if (!empty($variables['element']['#form_id'])) {
        $suggestions[] = 'form__' . $variables['element']['#form_id'];
    }
}
